main: dannygit.DannyGit
version: 0.1
author: DannyBoy and Jacobi
name: The first plugin

commands:
    hello:
        usage: /hello
        description: test to make sure our plugin works
    thorshammer:
        usage: /thorshammer
        description: add thors hammer to item in hand