main: dannygit.DannyGit
version: 0.1
author: DannyBoy and Jacobi
name: CustomEnchantments

commands:
    thorshammer:
        usage: /thorshammer
        description: add thors hammer to item in hand
    EnchantmentReload:
        usage: /EnchantmentReload
        description: reload the config files for CustomEnchantments
    poisionsword:
        usage: /poisionsword
        description: add poisionsword to your sword
    achoo:
        usage: /achoo
        description: add achoo to a slimeball
permissions:
    CustomEnchantments.SuperWeapon.get:
        default: op
    CustomEnchantments.SuperWeapon.Wield:
        default: op
    CustomEnchantments.get:
        defualt: op